/* eslint-disable react/react-in-jsx-scope */
import { useState, useCallback } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import { usePainter } from '../hooks/usePainter';
import { Canvas } from '../components/Canvas';
import { Toolbar } from '../components/Toolbar';
import { Intro } from '../components/Intro';

const Home: NextPage = () => {

  const [dateUrl, setDataUrl] = useState('#');
  const [{ canvas, isReady, ...state }, { init, ...api }] = usePainter();

  const handleDownload = useCallback(() => {
    if (!canvas || !canvas.current) return;

    setDataUrl(canvas.current.toDataURL('image/png'));
  }, [canvas]);

  const toolbarProps = { ...state, ...api, dateUrl, handleDownload };
  return (
		<>
    <div>
      <Head>
        <title>Data Lake</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
    <div>
      <Intro isReady={isReady} init={init} />
      <Toolbar {...toolbarProps} />
      <Canvas width={state.currentWidth} canvasRef={canvas} />
    </div>
		</>
	);
};

export default Home;
